#!/bin/sh
while read file
do
        case "$1" in
        "C-d")
                mv "$file" ~/.trash &&
                    notify-send "Moved file $file to ~/.trash" & ;;
        "C-c")
		[ -z "$destdir" ] && destdir="$(sed "s/\s.*#.*$//;/^\s*$/d" ${XDG_CONFIG_HOME:-$HOME/.config}/shell/bm-dirs | awk '{print $2}' | dmenu -l 20 -i -p "Copy file(s) to where?" | sed "s|~|$HOME|g")"
		[ ! -d "$destdir" ] && notify-send "$destdir is not a directory, cancelled." && exit
		cp "$file" "$destdir" && notify-send -i "$(readlink -f "$file")" "$file copied to $destdir." &
		;;
        "C-m")
		[ -z "$destdir" ] && destdir="$(sed "s/\s.*#.*$//;/^\s*$/d" ${XDG_CONFIG_HOME:-$HOME/.config}/shell/bm-dirs | awk '{print $2}' | dmenu -l 20 -i -p "Move file(s) to where?" | sed "s|~|$HOME|g")"
		[ ! -d "$destdir" ] && notify-send "$destdir is not a directory, cancelled." && exit
		mv "$file" "$destdir" && notify-send -i "$(readlink -f "$file")" "$file moved to $destdir." &
		;;
        "C-r")
                convert -rotate 90 "$file" "$file" ;;
        "C-w")
                xwallpaper --stretch "$file" &&
			        notify-send -i "$(readlink -f "$file")" "$file has been set as wallpaper" & ;;
        "C-y")
		        readlink -f "$file" | tr -d '\n' | xclip -selection clipboard &&
			        notify-send "$(readlink -f "$file") copied to clipboard" & ;;
        esac
done
